export const books = [
    {
        id: 1,
        title: "The Great Gatsby",
        category: "fiction",
        imageUrl: "https://example.com/images/the-great-gatsby.jpg",
        description: "A classic novel by F. Scott Fitzgerald about the American dream.",
        openUrl: "https://example.com/books/the-great-gatsby",
        downloadUrl: "https://example.com/downloads/the-great-gatsby.pdf",
    },
    {
        id: 2,
        title: "Sapiens: A Brief History of Humankind",
        category: "nonFiction",
        imageUrl: "https://example.com/images/sapiens.jpg",
        description: "An exploration of the history and impact of Homo sapiens.",
        openUrl: "https://example.com/books/sapiens",
        downloadUrl: "https://example.com/downloads/sapiens.pdf",
    },
    {
        id: 3,
        title: "A Brief History of Time",
        category: "science",
        imageUrl: "https://example.com/images/brief-history-of-time.jpg",
        description: "Stephen Hawking's exploration of the universe and time.",
        openUrl: "https://example.com/books/brief-history-of-time",
        downloadUrl: "https://example.com/downloads/brief-history-of-time.pdf",
    },
    {
        id: 4,
        title: "The Innovators",
        category: "technology",
        imageUrl: "https://example.com/images/the-innovators.jpg",
        description: "How a group of inventors created the digital revolution.",
        openUrl: "https://example.com/books/the-innovators",
        downloadUrl: "https://example.com/downloads/the-innovators.pdf",
    },
    {
        id: 5,
        title: "World War II: A Complete History",
        category: "history",
        imageUrl: "https://example.com/images/world-war-ii.jpg",
        description: "An in-depth account of World War II events and impact.",
        openUrl: "https://example.com/books/world-war-ii",
        downloadUrl: "https://example.com/downloads/world-war-ii.pdf",
    },
    {
        id: 6,
        title: "1984",
        category: "fiction",
        imageUrl: "https://example.com/images/1984.jpg",
        description: "George Orwell's dystopian novel about totalitarianism.",
        openUrl: "https://example.com/books/1984",
        downloadUrl: "https://example.com/downloads/1984.pdf",
    },
    {
        id: 7,
        title: "Clean Code",
        category: "technology",
        imageUrl: "https://example.com/images/clean-code.jpg",
        description: "A guide to writing clean and maintainable code by Robert C. Martin.",
        openUrl: "https://example.com/books/clean-code",
        downloadUrl: "https://example.com/downloads/clean-code.pdf",
    },
];